# Site settings
title: Rock Solid Engineering
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Long form tweets penned by Shale Craig, a University of Waterloo
  Software Engineering student.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shalecraig.github.io" # the base hostname & protocol for your site
twitter_username: __shale__
github_username:  shalecraig

# Build settings
markdown: kramdown

exclude: ['Gemfile', 'Gemfile.lock']

gems:
  - jemoji
